<?php

namespace Codec\Types;

class TInt extends ScaleInstance
{

    /**
     * @var integer $Width
     *
     */
    protected $Width;

    function decode ()
    {
    }

    function encode ($param)
    {
        return parent::encode($param); // TODO: Change the autogenerated stub
    }

}